### ISSUE TITLE
cursor: text on the label when in front of the input

### ISSUE THREAD

**Issue by aorylamballe** [mhartington/ion-md-input#14]
Hi,

I find more beautiful to add the carret (cursor: text) on the label when it is in front of the input text. So it looks like a real placeholder, transparent.

[codepen with cursor](http://codepen.io/anon/pen/ZGZqBg) / [codepen without cursor](http://codepen.io/mhartington/pen/xbgVjb) (original demo from mhartington). Place the cursor over an unfocused field to see the difference.

scss rule:

``` scss
.item-md-label {
  // ... then we insert at the end:
  input:not(:focus) ~ .input-label {
    cursor: text;
  }
}
```

Should we integrate it in this directive?

I thought a pull request (create a fork) for that was an overkill (I never tried yet this procedure :) )
